# Generated by Django 5.1.5 on 2026-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_free_answers_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_required', models.BooleanField(default=True, help_text='If disabled, all content is freely accessible without subscription.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
