# Generated by Django 5.1.5 on 2026-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('1month', '1 Month'), ('3month', '3 Months'), ('1year', '1 Year')], default='free', max_length=10),
        ),
    ]
