# Generated by Django 5.1.5 on 2026-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_tiers_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('management', 'Management')], max_length=15),
        ),
    ]
