# Generated by Django 5.1.5 on 2026-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_study_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='esewa_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, users pay via eSewa. If disabled, upgrades go through WhatsApp.'),
        ),
    ]
