# Generated by Django 5.1.5 on 2026-04-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_email_verification_otp_password_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_verification_enabled',
            field=models.BooleanField(default=True, help_text='If enabled, users must verify email via OTP on registration and get 4 free answer reveals. If disabled, no OTP required and free users get 0 answer reveals.'),
        ),
    ]
