# Generated by Django 5.1.5 on 2026-03-13 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('old_question', 'Old Question'), ('model_question', 'Model Question')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('sub_code', models.CharField(blank=True, max_length=10)),
                ('disclaimer', models.JSONField(blank=True, null=True)),
                ('has_disclaimer_2', models.BooleanField(default=False)),
                ('disclaimer_2', models.JSONField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20)),
                ('full_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('has_group', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_entries', to='content.subject')),
            ],
            options={
                'ordering': ['-year', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100)),
                ('group_disclaimer', models.TextField(blank=True)),
                ('marks_formula', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='questionbank.questionbankentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short Answer'), ('long', 'Long Answer'), ('passage', 'Passage'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True/False'), ('essay', 'Essay'), ('letter', 'Letter'), ('grammar', 'Grammar')], max_length=20)),
                ('content', models.JSONField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('marks_label', models.CharField(blank=True, max_length=20)),
                ('options', models.JSONField(default=list)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('bank', 'Question Bank'), ('manual', 'Manually Added')], default='bank', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='content.chapter')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionbank.questionbankentry')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionbank.questiongroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionbank.questionnode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
