# Generated by Django 5.1.5 on 2026-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnode',
            name='passage_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='questionnode',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short Answer'), ('long', 'Long Answer'), ('passage', 'Passage'), ('section', 'Section'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True/False'), ('essay', 'Essay'), ('letter', 'Letter'), ('grammar', 'Grammar')], max_length=20),
        ),
    ]
