# Generated by Django 5.1.5 on 2026-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_questiongroup_marks_marks_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankentry',
            name='is_nepali',
            field=models.BooleanField(default=False),
        ),
    ]
