# Generated by Django 5.1.5 on 2026-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0004_add_is_nepali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnode',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short Answer'), ('long', 'Long Answer'), ('passage', 'Passage'), ('section', 'Section'), ('fill_blank', 'Fill in the Blank'), ('true_false', 'True/False'), ('essay', 'Essay'), ('letter', 'Letter'), ('grammar', 'Grammar'), ('or_separator', 'OR Separator')], max_length=20),
        ),
    ]
