# Generated by Django 5.1.5 on 2026-03-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_chapter_optional_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='subject_books/'),
        ),
    ]
