# Generated by Django 5.1.5 on 2026-03-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subject_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
