# Generated by Django 5.1.5 on 2026-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_subject_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
