# Generated by Django 5.1.5 on 2026-04-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
