# Generated by Django 5.1.5 on 2026-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_area_order_alter_subject_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_full_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_pass_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus_university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
