# Generated by Django 5.1.5 on 2026-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_subject_syllabus_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_level',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=2),
        ),
    ]
